const sportsEmojis = [
  { image: require('../../../emoji-one/1f3be.png'), word: 'tennis' },
  { image: require('../../../emoji-one/1f3bf.png'), word: 'skiing' },
  { image: require('../../../emoji-one/1f3c0.png'), word: 'basketball' },
  { image: require('../../../emoji-one/1f3c1.png'), word: 'grand prix' },
  { image: require('../../../emoji-one/1f3c2.png'), word: 'snowboarding' },
  { image: [
    require('../../../emoji-one/1f3c3.png'),
    require('../../../emoji-one/1f3c3-1f3fb.png'),
    require('../../../emoji-one/1f3c3-1f3fc.png'),
    require('../../../emoji-one/1f3c3-1f3fd.png'),
    require('../../../emoji-one/1f3c3-1f3fe.png'),
    require('../../../emoji-one/1f3c3-1f3ff.png'),
  ], word: 'running' },
  { image: [
    require('../../../emoji-one/1f3c4.png'),
    require('../../../emoji-one/1f3c4-1f3fb.png'),
    require('../../../emoji-one/1f3c4-1f3fc.png'),
    require('../../../emoji-one/1f3c4-1f3fd.png'),
    require('../../../emoji-one/1f3c4-1f3fe.png'),
    require('../../../emoji-one/1f3c4-1f3ff.png'),
  ], word: 'surfing' },
  { image: require('../../../emoji-one/1f3c5.png'), word: 'medal' },
  { image: require('../../../emoji-one/1f3c6.png'), word: 'trophy' },
  { image: [
    require('../../../emoji-one/1f3c7.png'),
    require('../../../emoji-one/1f3c7-1f3fb.png'),
    require('../../../emoji-one/1f3c7-1f3fc.png'),
    require('../../../emoji-one/1f3c7-1f3fd.png'),
    require('../../../emoji-one/1f3c7-1f3fe.png'),
    require('../../../emoji-one/1f3c7-1f3ff.png'),
  ], word: 'horseriding' },
  { image: require('../../../emoji-one/1f3c8.png'), word: 'football' },
  { image: require('../../../emoji-one/1f3c9.png'), word: 'frisbee' },
  { image: [
    require('../../../emoji-one/1f3ca.png'),
    require('../../../emoji-one/1f3ca-1f3fb.png'),
    require('../../../emoji-one/1f3ca-1f3fc.png'),
    require('../../../emoji-one/1f3ca-1f3fd.png'),
    require('../../../emoji-one/1f3ca-1f3fe.png'),
    require('../../../emoji-one/1f3ca-1f3ff.png'),
  ], word: 'swimming' },
  { image: [
    require('../../../emoji-one/1f3cb.png'),
    require('../../../emoji-one/1f3cb-1f3fb.png'),
    require('../../../emoji-one/1f3cb-1f3fc.png'),
    require('../../../emoji-one/1f3cb-1f3fd.png'),
    require('../../../emoji-one/1f3cb-1f3fe.png'),
    require('../../../emoji-one/1f3cb-1f3ff.png'),
  ], word: 'weightlifting' },
  { image: require('../../../emoji-one/1f3cc.png'), word: 'golf' },
  { image: require('../../../emoji-one/1f3cd.png'), word: 'motorbiking' },
  { image: require('../../../emoji-one/1f3ce.png'), word: 'formula 1' },
  { image: require('../../../emoji-one/1f3cf.png'), word: 'cricket' },
  { image: require('../../../emoji-one/1f3d0.png'), word: 'netball' },
  { image: require('../../../emoji-one/1f3d1.png'), word: 'hockey' },
  { image: require('../../../emoji-one/1f3d2.png'), word: 'ice hockey' },
  { image: require('../../../emoji-one/1f3d3.png'), word: 'table tennis' },
  { image: require('../../../emoji-one/1f3f8.png'), word: 'badminton' },
  { image: require('../../../emoji-one/1f3f9.png'), word: 'archery' },
  { image: [
    require('../../../emoji-one/1f4aa.png'),
    require('../../../emoji-one/1f4aa-1f3fb.png'),
    require('../../../emoji-one/1f4aa-1f3fc.png'),
    require('../../../emoji-one/1f4aa-1f3fd.png'),
    require('../../../emoji-one/1f4aa-1f3fe.png'),
    require('../../../emoji-one/1f4aa-1f3ff.png'),
  ], word: 'bodybuilding' },
  { image: [
    require('../../../emoji-one/1f6b4.png'),
    require('../../../emoji-one/1f6b4-1f3fb.png'),
    require('../../../emoji-one/1f6b4-1f3fc.png'),
    require('../../../emoji-one/1f6b4-1f3fd.png'),
    require('../../../emoji-one/1f6b4-1f3fe.png'),
    require('../../../emoji-one/1f6b4-1f3ff.png'),
  ], word: 'cycling' },
  { image: [
    require('../../../emoji-one/1f6b5.png'),
    require('../../../emoji-one/1f6b5-1f3fb.png'),
    require('../../../emoji-one/1f6b5-1f3fc.png'),
    require('../../../emoji-one/1f6b5-1f3fd.png'),
    require('../../../emoji-one/1f6b5-1f3fe.png'),
    require('../../../emoji-one/1f6b5-1f3ff.png'),
  ], word: 'mountain biking' },
  { image: [
    require('../../../emoji-one/1f6b6.png'),
    require('../../../emoji-one/1f6b6-1f3fb.png'),
    require('../../../emoji-one/1f6b6-1f3fc.png'),
    require('../../../emoji-one/1f6b6-1f3fd.png'),
    require('../../../emoji-one/1f6b6-1f3fe.png'),
    require('../../../emoji-one/1f6b6-1f3ff.png'),
  ], word: 'walking' },
]

export default sportsEmojis